### ISSUE TITLE
Is there a way to make this work on dolphin?

### ISSUE THREAD

**Issue by DrKoneko** [Naim2000/photo_upgrader#1]
I can't seem to get it to work on dolphin. It just crashes.

**Comment by TCAtrevor** [comment]
Did it work for you? I'm trying to get it to work there as well. I just get a cryptic message: `Failed! (-2011)`

**Comment by Naim2000** [comment]
Oh hi. Unfortunately it won't work on dolphin because I have to modify the TMD and ticket, and that makes the signature check fail
Better approach is a script that runs on PC that creates a patched WAD, like [Wii_Mii_Channel_Unix.command](https://wii.hacks.guide/assets/files/Wii_Mii_Channel_Unix.command) except it downloads the Photo channel and changes the Title ID
